### ISSUE TITLE
golang scheduler

### ISSUE THREAD

**Issue by nosarthur** [polaris1119/golangweekly#1]
https://www.ardanlabs.com/blog/2018/08/scheduling-in-go-part1.html

**Comment by polaris1119** [comment]
https://studygolang.com/articles/14264
https://studygolang.com/articles/15316
https://studygolang.com/articles/17014

这个系列的3篇，GCTT 都有翻译

**Comment by busgo** [comment]
分布式任务调度平台
https://studygolang.com/p/busgo

**Comment by polaris1119** [comment]
@busgo 好的，下次可以新开一个 issue

**Comment by busgo** [comment]
> @busgo 好的，下次可以新开一个 issue

好的已添加
