### ISSUE TITLE
go语言500行后台代码实现一轻量级博客系统

### ISSUE THREAD

**Issue by yangyongzhen** [polaris1119/golangweekly#10]
后台代码量极小，使用Golang语言，总共不到五百行的后台代码。
后台使用了Golang+ Gin web框架，整个后台代码就一个main.go文件。
前端使用了流行的markdown-it(MarkDown渲染),highlight.js（语法高亮）和mermaid.js（画流程图、时序图等的js库）组件。
留言评论功能，界面爬取自网络大神阮一峰的个人博客界面样式，改了过来。
演示地址链接：http://121.36.253.86/
oschina收录地址：https://www.oschina.net/p/tinybg
博客说明地址：https://blog.csdn.net/yyz_1987/article/details/106228599
开源地址：
https://gitee.com/yyz116/tinybg
https://github.com/yangyongzhen/tinybg
但功能一点也不弱。
功能：
1.文章的分页展示。

2.支持文章中表格，图片的显示和代码的语法高亮。

3.支持文章的无限制分类。

4.支持站点访问量统计，文章浏览量统计，按时间和按点击量排序展示最新文章，最热文章。

5.文章留言评论，最新评论等功能。

安装教程
直接执行 go run main.go即可。
或者go bulid main.go 后，把可执行文件main跑起来即可。无需建库，建表，安装部署超级简单。
使用说明
发布文章就是在电脑上写好md格式的文件，提交到服务器的posts目录。

**Comment by polaris1119** [comment]
已收录 第 45 期
