### ISSUE TITLE
go语言系统测试覆盖率收集利器goc

### ISSUE THREAD

**Issue by CarlJi** [polaris1119/golangweekly#11]
项目地址:  https://github.com/qiniu/goc

在goc以前，业界在做覆盖率收集时，都是采用一种很tricky的方式来做，有种种不优雅的地方。而goc能够让被测程序在运行时就可以收集系统测试覆盖率，当属比较优雅。且此种方式，也为go语言的精准测试方向，展现了无限可能。

笔者写了偏较为详细的介绍文章：https://mp.weixin.qq.com/s/NUApZZnQALkzvZtHFE_8Zw

欢迎收录。

**Comment by polaris1119** [comment]
收到~

**Comment by polaris1119** [comment]
已收录
