### ISSUE TITLE
【开源自荐】go-optioner：一个根据结构体定义自动生成函数选项模式（functional options pattern）代码的工具

### ISSUE THREAD

**Issue by chenmingyong0423** [polaris1119/golangweekly#112]
https://github.com/chenmingyong0423/go-optioner

**Comment by googs1025** [comment]
有趣的项目，自己平时也喜欢用选项模式，
不过在字段多的情况确实很头大，哈哈
已star！

**Comment by chenmingyong0423** [comment]
> 有趣的项目，自己平时也喜欢用选项模式， 不过在字段多的情况确实很头大，哈哈 已star！

哈哈，英雄所见略同

**Comment by lxzan** [comment]
> 有趣的项目，自己平时也喜欢用选项模式， 不过在字段多的情况确实很头大，哈哈 已star！

gws最开始就是用的option模式, 后面server/client option实在太多只能回归结构体配置了
