### ISSUE TITLE
【开源自荐】AICodeConvert，代码转换工具

### ISSUE THREAD

**Issue by JustAIGithub** [polaris1119/golangweekly#113]
开源的代码转换工具，使用GPT实现；
[AICodeConvert](https://aicodeconvert.com/)
主要包含两个功能：
1.自然语言转代码，描述需求就生成对应的代码
2.把代码一键转换为另一种代码语言实现；

**Comment by polaris1119** [comment]
已收录：[issue-198.md](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-198.md)
