### ISSUE TITLE
【开源自荐】基于golang实现的k8s多集群多资源的简易informer监听

### ISSUE THREAD

**Issue by googs1025** [polaris1119/golangweekly#115]
项目简介：一般在kubernetes中的client-go的仅有单集群且单资源的监听demo。基于这个问题，本项目采用client-go包进行扩展封装，实现"多集群"且"多资源"的 informer机制。调用方仅需要维护config.yaml配置文件与handlerFunc即可。
支持功能：
1. 可提供"多集群"informer配置。
2. 可提供多资源informer，目前支持pods、services、configmaps、deployments、events等。
3. 可支持在配置namespace时，使用all字段来监听所有namespace的特定资源。
4. 可支持跳过tls认证过程直接调用informer
5. 可支持回传监听到资源对象的runtime.Object实例

项目地址：https://github.com/Kubernetes-Learning-Playground/multi-cluster-informer

**Comment by polaris1119** [comment]
已收录：[issue-198.md](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-198.md)
