### ISSUE TITLE
【开源自荐】mongo-plus: 简易的mongodb库

### ISSUE THREAD

**Issue by here-Leslie-Lau** [polaris1119/golangweekly#117]
项目地址:
https://github.com/here-Leslie-Lau/mongo-plus

项目简介:
- 调用链操作, 自由组合条件
- api友好
- 支持Context
- 开箱即用
- 分页查询支持
- 简易的聚合(aggregate)支持
- 持续更新ing

**Comment by polaris1119** [comment]
已收录：[issue-198.md](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-198.md)
