### ISSUE TITLE
[推荐] cassandra-web

### ISSUE THREAD

**Issue by yulintsai** [polaris1119/golangweekly#14]
https://github.com/orzhaha/cassandra-web

**cassandra-web** 是一个以golang&vue.js为基础，以Web-Base方式架构在网站主机上的cassandra的资料库管理工具，让管理者可用Web介面管理cassandra资料库。

此外也支援scylla，也提供Chart可以使用Helm进行部署。

### Features
* Theme Dark
* Table Row Prev Next Page
* Table Row Edit
* Table Row filter
* Table Row Delete
* Table Rown Find
* Table Definition
* Table Export
* Table Import
* CQL Query

**Comment by polaris1119** [comment]
收录第 58 期
