### ISSUE TITLE
62期 go101 const s ="Go101.org" 换成 var s ="Go101.org" 结果为 0 0

### ISSUE THREAD

**Issue by xu1260114313** [polaris1119/golangweekly#16]
![f474d36d60b9f13466973a39fe8c569](https://user-images.githubusercontent.com/21236047/95042113-70985c00-070b-11eb-84e2-81788ba971d0.png)

**Comment by xu1260114313** [comment]
为什么从const声明换成了var声明，结果会不一样？

**Comment by polaris1119** [comment]
见 https://mp.weixin.qq.com/s/GqdzjXuaZOmjqit32Vxuzg
