### ISSUE TITLE
[自荐] 专注于 Go 高性能编程实践的开源电子书项目

### ISSUE THREAD

**Issue by geektutu** [polaris1119/golangweekly#23]
- Github 地址：[high-performance-go](https://github.com/geektutu/high-performance-go)
- 项目主页：[Go 语言高性能编程](https://geektutu.com/post/high-performance-go.html)

**Comment by polaris1119** [comment]
已在[第 74 期](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-074.md)发布
