### ISSUE TITLE
[软件更新资讯] Excelize 2.3.2 发布，Go 语言 Excel 文档基础库，2021 年首个更新

### ISSUE THREAD

**Issue by xuri** [polaris1119/golangweekly#27]
[Excelize](https://github.com/xuri/excelize) 是 Go 语言编写的用于操作 Office Excel 文档基础库，基于 ECMA-376，ISO/IEC 29500 国际标准。可以使用它来读取、写入由 Microsoft Excel™ 2007 及以上版本创建的电子表格文档。支持 XLSX / XLSM / XLTM 等多种文档格式，高度兼容带有样式、图片(表)、透视表、切片器等复杂组件的文档，并提供流式读写 API，用于处理包含大规模数据的工作簿。可应用于各类报表平台、云计算、边缘计算等系统。

<p align="center"><img src="https://user-images.githubusercontent.com/2809468/104084356-45308a80-5281-11eb-8725-988912401cce.png" width="500" alt="Go Excelize v2.3.2"></p>

2021年1月4日，社区正式发布了 2.3.2 版本，该版本包含了多项新增功能、错误修复和兼容性提升优化：[https://xuri.me/excelize/zh-hans/releases/v2.3.2.html](https://xuri.me/excelize/zh-hans/releases/v2.3.2.html)

**Comment by polaris1119** [comment]
已发布
