### ISSUE TITLE
推荐一篇英文文章rust和go的对比

### ISSUE THREAD

**Issue by west789** [polaris1119/golangweekly#37]
【英文基础不好，无法理解文章含义，希望能够翻译该篇文章】
[Rust vs. Go: Why They’re Better Together](https://thenewstack.io/rust-vs-go-why-theyre-better-together/)

**Comment by lhlyu** [comment]
知乎有人翻译了，[链接](https://zhuanlan.zhihu.com/p/357435271)

**Comment by west789** [comment]
> 知乎有人翻译了，[链接](https://zhuanlan.zhihu.com/p/357435271)

感谢，已关闭issue
