### ISSUE TITLE
【文章推荐】图解Go字符串底层存储原理及常见错误

### ISSUE THREAD

**Issue by goxuetang** [polaris1119/golangweekly#50]
文章地址：https://mp.weixin.qq.com/s/y2gSmjeUp6UdOs84iONOfw
用图解的方式介绍了string的底层原理以及rune类型。同时介绍了string在使用中常见的错误

**Comment by Spongecaptain** [comment]
你和 幼麟实验室 为什么用相同的头像？

**Comment by goxuetang** [comment]
> 你和 幼麟实验室 为什么用相同的头像？ @goxuetang

这个纯属巧合。我起公众号名字的时候 是Go学堂，学堂代表的学习，就在往网上找了一个图片。没想到冲突了。
