### ISSUE TITLE
go 语言分布式事务框架推荐

### ISSUE THREAD

**Issue by dk-lockdown** [polaris1119/golangweekly#67]
文章介绍：https://cectc.github.io/dbpack-doc/#/blogs/eda-design
项目地址：https://github.com/CECTC/hptx
samples：https://github.com/CECTC/hptx-samples/tree/main/http

**Comment by polaris1119** [comment]
发布在 https://github.com/polaris1119/golangweekly/blob/master/docs/issue-151.md
