### ISSUE TITLE
开源项目 gev ：一个轻量、比 net 库更快的基于 Reactor 模式的非阻塞 TCP 网络库

### ISSUE THREAD

**Issue by Allenxuxu** [polaris1119/golangweekly#7]
https://github.com/Allenxuxu/gev

`gev` 是一个轻量、快速的基于 Reactor 模式的非阻塞 TCP 网络库，支持自定义协议，轻松快速搭建高性能服务器。

## 特点

- 基于 epoll 和 kqueue 实现的高性能事件循环
- 支持多核多线程
- 动态扩容 Ring Buffer 实现的读写缓冲区
- 异步读写
- SO_REUSEPORT 端口重用支持
- 支持 WebSocket
- 支持定时任务，延时任务
- 支持自定义协议

**Comment by polaris1119** [comment]
已在 17 期 发布
