### ISSUE TITLE
Make Releases or Pull Requests for each release

### ISSUE THREAD

**Issue by thatInfrastructureGuy** [polaris1119/golangweekly#73]
I want to get notified via GitHub notifications whenever a new issue is released. I want to only `Watch` for new releases. This can either be done if I follow new `Releases` or if I follow `Pull Requests`. 

<img width="297" alt="Screen Shot 2022-07-07 at 11 33 48 AM" src="https://user-images.githubusercontent.com/5376494/177845375-7fe6c830-9499-46a0-81f4-cd3943fab735.png">

Hence, if you could make a pull request or Release whenever releasing a new issue, it would be appreciated.

Thanks for doing this project!

**Comment by polaris1119** [comment]
done
