### ISSUE TITLE
【开源自荐】gonacli是一个快速使用 Golang 语言编写 NodeJS Addon 扩展的开发工具

### ISSUE THREAD

**Issue by wenlng** [polaris1119/golangweekly#87]
项目名称：gonacli 开发工具

项目地址：https://github.com/wenlng/gonacli

网站地址：http://witkeycode.com/s/Do6cZUb4P

项目简介：GONACLI 是一个快速使用 Golang 开发 NodeJS Addon 扩展的开发工具，开发者只需要专注在 Golang 的开发，无需关心与 NodeJS 的 Bridge 桥接层的实现，支持 JavaScript 同步调用和异步回调等。

项目截图：
<img src="http://47.104.180.148/gonacli/gonacli_poster_v3.jpg"/>

**Comment by polaris1119** [comment]
[186期](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-186.md) 发布
