### ISSUE TITLE
【开源自荐】trzsz ( trz / tsz ) 是兼容 tmux 的 rz / sz，有进度条，支持目录传输，支持拖动上传。

### ISSUE THREAD

**Issue by lonnywong** [polaris1119/golangweekly#89]
- 项目名称：trzsz

- 项目地址：https://github.com/trzsz/trzsz-go

- 项目简介：

  trzsz ( trz / tsz ) 始于 iTerm2 + tmux 用不了 rz / sz ，使用 Python 开发，兼容 tmux ，有进度条，支持目录传输，支持拖动上传。github: https://github.com/trzsz/trzsz 。

  为了支持更多的原生终端使用 trzsz ( trz / tsz )，开发了 go 版本 https://github.com/trzsz/trzsz-go 。

- 相比 lrzsz ( rz / sz )，trzsz ( trz / tsz ）具有以下优点：

  * 支持 **tmux**，包括 tmux 普通模式，以及与 iTerm2 集成的 tmux 命令模式。
  * 支持 **传输目录**，`trz -d` 命令上传目录，`tsz -d xxx` 命令下载 xxx 目录。
  * 支持 **Windows**，不仅可在 Windows 客户端使用，也可在 Windows ssh 服务器使用。
  * 支持 **原生终端**，不需要原生终端做支持，只要使用 `trzsz ssh x.x.x.x` 登录即可。
  * 支持 **web 终端**，通过 web 浏览器在本地与服务器之间传输目录和文件。
  * 支持 **拖动上传**，将文件和目录拖到终端窗口即可上传到远程服务器。
  * 支持 **进度条**，显示当前正在传输的文件名、进度、大小、速度和剩余时间等。
  * 更好的 **交互体验**，传输成功或出错时显示友好的结果，`ctrl + c` 优雅中止。

- 项目截图：

![drag_files](https://user-images.githubusercontent.com/20320324/209072962-73ab2660-9e13-4368-9864-8fd1cf52f8c1.gif)

![ubuntu_trzsz](https://user-images.githubusercontent.com/20320324/209073871-92d5ac86-2926-48cd-9a47-457bb98c270b.gif)

![cmd_trzsz](https://user-images.githubusercontent.com/20320324/209073892-8f56baea-bbb8-4bfd-b3e1-ce971fc71626.gif)

**Comment by lonnywong** [comment]
[trzsz-go v1.1.0](https://github.com/trzsz/trzsz-go) 用多协程流水线，将读文件、压缩、base64 编码、发送、接收、base64 解码、解压缩、写文件等进行并行处理，大幅度提高了传输速度。

流水线的核心代码可参考：https://github.com/trzsz/trzsz-go/blob/main/trzsz/pipeline.go

参考文献：
1 、https://go.dev/blog/pipelines
2 、https://go.dev/blog/context

**Comment by lonnywong** [comment]
[trzsz-go v1.1.0](https://github.com/trzsz/trzsz-go) 新增了支持跳板机运行 tmux 普通模式的场景（ 原来只支持 tmux 命令模式的）：

1 、开始 trzsz ( trz / tsz ) 只支持 iTerm2 中使用 tmux -CC 命令模式的场景（ 也是我自己常用的 ）。
典型用法： `[客户端]` `iTerm2` 👉 `ssh xxx` 👉 `[服务器]` `tmux -CC` 👉 `trz / tsz`

2 、后来 trzsz 支持在服务器上 tmux 普通模式的场景。
典型用法： `[客户端]` `iTerm2 等` 👉 `ssh xxx` 👉 `[服务器]` `tmux` 👉 `trz / tsz`

3 、再后来 go 版 trzsz 支持 tmux 运行在客户端的场景。
典型用法： `[客户端]` `tmux` 👉 `trzsz ssh xxx` 👉 `[服务器]` `trz / tsz`

4 、当在中间（ 如跳板机 ）上运行 tmux ，之前只支持 iTerm2 + tmux -CC 命令模式。
典型用法： `[客户端]` `iTerm2` 👉 `ssh xxx` 👉 `[跳板机]` `tmux -CC` 👉 `ssh xxx` 👉 `[服务器]` `trz / tsz`

5 、[trzsz-go v1.1.0](https://github.com/trzsz/trzsz-go) 支持在中间（ 如跳板机 ）上运行 tmux 普通模式。
典型用法： `[客户端]` `trzsz ssh xxx` 👉 `[跳板机]` `tmux` 👉 `trzsz -r ssh xxx` 👉 `[服务器]` `trz / tsz`

**重点在于，在跳板机运行 tmux 之后，要用 `trzsz -r ssh` 登录到下一级服务器。**

**Comment by polaris1119** [comment]
[186期](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-186.md) 发布
