### ISSUE TITLE
【开源自荐】QuarkGo兼容：Gin、Hertz、Fiber、Zero、Echo等框架的管理后台 v1.2.24 发布

### ISSUE THREAD

**Issue by quarkcms** [polaris1119/golangweekly#96]
介绍
QuarkGO 是一款兼容：Gin、Hertz、Fiber、Zero、Echo框架的后台脚手架；它提供的丰富组件，能帮助您使用很少的代码就能搭建出功能完善的应用系统。

欢迎各位Star
https://github.com/quarkcms/quark-go

相关项目
[QuarkSmart](https://github.com/quarkcms/quark-smart) 单体应用
[QuarkMicro](https://github.com/quarkcms/quark-go) 微服务应用
[QuarkLite](https://github.com/quarkcms/quark-lite) 应用布局

演示站点

地址：http://smart.quarkcms.com/admin/#/
账号：administrator
密码：123456

**Comment by polaris1119** [comment]
[186期](https://github.com/polaris1119/golangweekly/blob/master/docs/issue-186.md) 发布
