### ISSUE TITLE
[开源推荐] apicat 可以使用ai生成接口文档的接口管理工具

### ISSUE THREAD

**Issue by afocus** [polaris1119/golangweekly#98]
项目地址 [https://github.com/apicat/apicat](https://github.com/apicat/apicat)

使用go + vue + openapi 实现的一套开源接口管理工具 支持openapi导入导出

**Comment by polaris1119** [comment]
已收录：<https://github.com/polaris1119/golangweekly/blob/master/docs/issue-190.md>
